### ISSUE TITLE
mailman-web appears to lack the python-mysql package

### ISSUE THREAD

**Issue by JonasT** [maxking/docker-mailman#136]
mailman-web appears to lack the python-mysql package. At least I can't get the MySQL backend to work:

```
mailman-web_1     | Traceback (most recent call last):
mailman-web_1     |   File "manage.py", line 10, in <module>
mailman-web_1     |     execute_from_command_line(sys.argv)
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
mailman-web_1     |     utility.execute()
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
mailman-web_1     |     django.setup()
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
mailman-web_1     |     apps.populate(settings.INSTALLED_APPS)
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
mailman-web_1     |     app_config.import_models(all_models)
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
mailman-web_1     |     self.models_module = import_module(models_module_name)
mailman-web_1     |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
mailman-web_1     |     __import__(name)
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/hyperkitty/models/__init__.py", line 27, in <module>
mailman-web_1     |     from .category import ThreadCategory
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/hyperkitty/models/category.py", line 30, in <module>
mailman-web_1     |     class ThreadCategory(models.Model):
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 119, in __new__
mailman-web_1     |     new_class.add_to_class('_meta', Options(meta, app_label))
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 316, in add_to_class
mailman-web_1     |     value.contribute_to_class(cls, name)
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/db/models/options.py", line 214, in contribute_to_class
mailman-web_1     |     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/db/__init__.py", line 36, in __getattr__
mailman-web_1     |     return getattr(connections[DEFAULT_DB_ALIAS], item)
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 211, in __getitem__
mailman-web_1     |     backend = load_backend(db['ENGINE'])
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 115, in load_backend
mailman-web_1     |     return import_module('%s.base' % backend_name)
mailman-web_1     |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
mailman-web_1     |     __import__(name)
mailman-web_1     |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 28, in <module>
mailman-web_1     |     raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
mailman-web_1     | django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb
```

**Comment by JonasT** [comment]
The mailman-core container seems to have a similar problem:

```
mailman-core_1    | Traceback (most recent call last):
mailman-core_1    |   File "/usr/local/bin/mailman", line 11, in <module>
mailman-core_1    |     sys.exit(main())
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/bin/mailman.py", line 97, in main
mailman-core_1    |     initialize(config_path)
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/core/initialize.py", line 185, in initialize
mailman-core_1    |     initialize_2(propagate_logs=propagate_logs)
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/core/initialize.py", line 156, in initialize_2
mailman-core_1    |     config.db = getUtility(IDatabaseFactory, utility_name).create()
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/database/factory.py", line 52, in create
mailman-core_1    |     database = call_name(database_class)
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/utilities/modules.py", line 54, in call_name
mailman-core_1    |     named_callable = find_name(dotted_name)
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/utilities/modules.py", line 37, in find_name
mailman-core_1    |     __import__(package_path)
mailman-core_1    | ValueError: Empty module name
```

**Comment by maxking** [comment]
Yes, this is a known issue and there is some discussion on it https://github.com/maxking/docker-mailman/pull/123

**Comment by JonasT** [comment]
PostgreSQL unfortunately still doesn't upgrade in-place and therefore is a bit of a pain on major upgrades. MySQL / mariadb is much more docker / low-maintenance friendly in that regard.. so it'd be nice to have :smile:
