### ISSUE TITLE
mailman-core doesn't infer proper default for DATABASE_CLASS from DATABASE_URL

### ISSUE THREAD

**Issue by ghost** [maxking/docker-mailman#137]
The mailman-core apparently doesn't infer a proper default for `DATABASE_CLASS` from `DATABASE_URL`, at least for mysql dbs. Instead, this is what happens when only `DATABASE_URL` with a value of "mysql://.." is specified:
```
mailman-core_1    | Traceback (most recent call last):
mailman-core_1    |   File "/usr/local/bin/mailman", line 11, in <module>
mailman-core_1    |     sys.exit(main())
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/bin/mailman.py", line 97, in main
mailman-core_1    |     initialize(config_path)
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/core/initialize.py", line 185, in initialize
mailman-core_1    |     initialize_2(propagate_logs=propagate_logs)
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/core/initialize.py", line 156, in initialize_2
mailman-core_1    |     config.db = getUtility(IDatabaseFactory, utility_name).create()
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/database/factory.py", line 52, in create
mailman-core_1    |     database = call_name(database_class)
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/utilities/modules.py", line 54, in call_name
mailman-core_1    |     named_callable = find_name(dotted_name)
mailman-core_1    |   File "/usr/local/lib/python3.6/site-packages/mailman/utilities/modules.py", line 37, in find_name
mailman-core_1    |     __import__(package_path)
mailman-core_1    | ValueError: Empty module name
```
Since specifying `DATABASE_CLASS` in addition seems quite redundant and unnecessary given the required information is already in `DATABASE_URL`, I suggest that this is handled by a container startup script with a reasonable default depending on the given URL protocol. ("postgres://..", "mysql://..", ..)

**Comment by JonasT** [comment]
I made a pull request for this now: https://github.com/maxking/docker-mailman/pull/150
