### ISSUE TITLE
Server Error (500) page when try to connect to HyperKitty

### ISSUE THREAD

**Issue by pokapow** [maxking/docker-mailman#204]
When I try to connect for the first time to mailman web page, I have to click in "Forget password" to get the admin password, and then I have this error:
Server Error (500)
In a white page ...
If I try to register new user, same error...
I found nothing in logs neither mailman-web and mailman-core ...

How can I debug this ?

**Comment by maxking** [comment]
I most likely is like this because your Email isn't setup, Forgot Password will try to send you  and email and if the email backend isn't setup, you should get this error.

Sadly, logs don't show up in `docker logs` for both the containers, it is something that needs to be fixed. If you check the logs at `/opt/mailman/web/logs/mailmanweb.log` or other .log files in that directory, I am sure you will find some information.

Hopefully that helps!

**Comment by pokapow** [comment]
This is what's log in `/opt/mailman/web/logs/mailmanweb.log`
```
ERROR 2017-12-21 13:09:43,807 32 django.request Internal Server Error: /accounts/password/reset/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/allauth/account/views.py", line 102, in post
    response = self.form_valid(form)
  File "/usr/local/lib/python2.7/site-packages/allauth/account/views.py", line 639, in form_valid
    form.save(self.request)
  File "/usr/local/lib/python2.7/site-packages/allauth/account/forms.py", line 520, in save
    context)
  File "/usr/local/lib/python2.7/site-packages/allauth/account/adapter.py", line 140, in send_mail
    msg.send()
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/message.py", line 342, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
    sent = self._send(message)
  File "/usr/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 123, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/local/lib/python2.7/smtplib.py", line 748, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {u'poka@exemple.com': (504, '5.5.2 <mailman-web>: Helo command rejected: need fully-qualified hostname')}
```

**Comment by maxking** [comment]
It looks like some error in your SMTP settings for Django.

Can you show me how does it look like?

**Comment by pokapow** [comment]
When try de register, login or reset password, this is the error:

<a href="https://www.hostingpics.net/viewer.php?id=813466Capturedu20171222124156.png"><img src="https://img15.hostingpics.net/thumbs/mini_813466Capturedu20171222124156.png" alt="Heberger image" /></a>

But when register, le registration seems to be ok in mailman database, account are created.

**Comment by maxking** [comment]
I meant the settings.

What environment variables are you using to configure SMTP settings to send out emails?

**Comment by simonschllng** [comment]
I'm having the same troubles and tried to configure SMTP like explained under 
> To configure the mailman-web container to send emails, add this to your settings_local.py.:

here: https://asynchronous.in/docker-mailman/#mailman-core

What is required on the host system when it is used as SMTP host. Which kind of smtp server do we need?

**Comment by brianemwd** [comment]
I believe either EXIM or Postfix works well with maxkings' setup.

**Comment by maxking** [comment]
That's correct, the container setup currently supports Exim or Postfix and the README. How to setup each  of them completely is out of scope for this guide though, only the options specific to Mailman have been mentioned in the docs.
