### ISSUE TITLE
Old Error has Returned

### ISSUE THREAD

**Issue by brianemwd** [maxking/docker-mailman#229]
Here is the error I get when I run:

docker logs mailman-web:

Traceback (most recent call last):
File "manage.py", line 10, in <module>
execute_from_command_line(sys.argv)
File
"/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py",
line 363, in execute_from_command_line
utility.execute()
File
"/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py",
line 307, in execute
settings.INSTALLED_APPS
File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line
56, in __getattr__
self._setup(name)
File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line
41, in _setup
self._wrapped = Settings(settings_module)
File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line
110, in __init__
mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in
import_module
__import__(name)
File "/opt/mailman-web/settings.py", line 60, in <module>
MAILMAN_HOST_IP_AUTO = socket.gethostbyname('mailman-core')
socket.gaierror: [Errno -2] Name does not resolve

**Comment by maxking** [comment]
I need to release 0.1 with new changes to fix this one. It has already been fixed in the master.
