### ISSUE TITLE
Hyperkitty Search box result in error 500

### ISSUE THREAD

**Issue by Dragnell87** [maxking/docker-mailman#236]
Running Hyperkkity  1.1.4 if i try to search for anything a got a error 500

Looking for some info i got this from mailmanweb.log

```
ERROR 2018-04-24 17:33:35,234 286 hyperkitty.lib.utils Failed to update the fulltext index: ord() expected a character, but string of length 0 found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/hyperkitty/lib/utils.py", line 186, in run_with_lock
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/hyperkitty/search_indexes.py", line 87, in update_index
    update_cmd.update_backend("hyperkitty", "default")
  File "/usr/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 257, in update_backend
    commit=self.commit, max_retries=self.max_retries)
  File "/usr/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 84, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/usr/local/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py", line 178, in update
    self.setup()
  File "/usr/local/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py", line 126, in setup
    self.index = self.storage.open_index(schema=self.schema)
  File "/usr/local/lib/python2.7/site-packages/whoosh/filedb/filestore.py", line 176, in open_index
    return indexclass(self, schema=schema, indexname=indexname)
  File "/usr/local/lib/python2.7/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/usr/local/lib/python2.7/site-packages/whoosh/index.py", line 632, in read
    check_size("int", _INT_SIZE)
  File "/usr/local/lib/python2.7/site-packages/whoosh/index.py", line 626, in check_size
    sz = stream.read_varint()
  File "/usr/local/lib/python2.7/site-packages/whoosh/filedb/structfile.py", line 191, in read_varint
    return read_varint(self.read)
  File "/usr/local/lib/python2.7/site-packages/whoosh/util/varints.py", line 102, in read_varint
    b = ord(readfn(1))
TypeError: ord() expected a character, but string of length 0 found
```
I suspect that at some point archiving some mail something went wrong, but no sure. Any idea how to fix

**Comment by maxking** [comment]
This SO question looks relevant to me.

https://stackoverflow.com/questions/7949555/strange-error-adding-to-whoosh-index

**Comment by Dragnell87** [comment]
Thanks
Deleting the content of /opt/mailman-web-data/fulltext_index/ solved the problem.

Closing

**Comment by maxking** [comment]
Awesome!

**Comment by djgalloway** [comment]
> Thanks
> Deleting the content of /opt/mailman-web-data/fulltext_index/ solved the problem.
> 
> Closing

Any idea how safe this is to do?  That directory on my installation keeps filling up (270GB and counting :open_mouth:)and taking down my server.

**Comment by maxking** [comment]
It is completely safe, it is just search index and can be rebuilt. Although, it takes up a lot of time to do so.

Docs for fulltext index needs updating but it will be much nicer to attach an elasticsearch container along with Mailman and use that instead of the current Python library to do searches.
