### ISSUE TITLE
Postorius container failing to start (migrations failed)

### ISSUE THREAD

**Issue by danil-smirnov** [maxking/docker-mailman#309]
When try to start maxking/postorius container using the [related configuration file](https://github.com/maxking/docker-mailman/blob/master/docker-compose-postorius.yaml), I'm getting the following error:

```
settings_local.py not found, it is highly recommended that you provide one
Using default configuration to run.

0 static files copied to '/opt/mailman-web-data/static', 150 unmodified.
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, django_mailman3, openid, postorius, sessions, sites, socialaccount
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: syntax error at or near "WITH ORDINALITY"
LINE 6:                     FROM unnest(c.conkey) WITH ORDINALITY co...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 150, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 467, in remove_field
    fk_names = self._constraint_names(model, [field.column], foreign_key=True)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 1029, in _constraint_names
    constraints = self.connection.introspection.get_constraints(cursor, model._meta.db_table)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/introspection.py", line 158, in get_constraints
    """, ["public", table_name])
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: syntax error at or near "WITH ORDINALITY"
LINE 6:                     FROM unnest(c.conkey) WITH ORDINALITY co...
                                                  ^

  Applying postorius.0003_drop_addressconfirmationprofile...
```

My database is:
_PostgreSQL 9.2.24 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit_

**Comment by maxking** [comment]
This is the first time I have seen this.

**Comment by maxking** [comment]
This is most certainly a Django bug, we don't generate SQL queries at all, we might be able to fix this by jumping to a newer or older release of Django. Let me see what I can do.

**Comment by maxking** [comment]
Can you try installing an older version of Django inside the container?

You can enter the container with:

```docker exec -u root -it mailman-web bash```

And the install Django with:

```pip install Django==2.1.6```

The latest is 2.1.7, so maybe we can try, 2.1.6 (go back) and go forward (`pip install https://github.com/django/django/archive/master.zip`) to install the git master.

**Comment by danil-smirnov** [comment]
Unfortunately no, as container does not start at all

**Comment by maxking** [comment]
You should be able to start up the container by overriding some stuff:

Can you try:

```
docker run --entrypoint 'bash -c'  -it mailman-web bash
```

This should basically prevent the startup script from running at all and you will be able to enter using a `docker exec` command then as root and then install a new version.

**Comment by danil-smirnov** [comment]
Okay, `docker run` command expects docker image, not container name, and my image is _maxking/postorius_. Also I wasn't able to run your code at all, this is my variant:

`docker run -it --entrypoint /bin/bash maxking/postorius:rolling
`
If I do `pip install` inside the container, I get this:

```
bash-4.3# pip install Django==2.1.6
Collecting Django==2.1.6
  Could not find a version that satisfies the requirement Django==2.1.6 (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16, 1.11.17, 1.11.18, 1.11.20, 2.0a1, 2.0b1, 2.0rc1, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.12, 2.0.13, 2.1a1, 2.1b1, 2.1rc1, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.7, 2.2a1, 2.2b1)
No matching distribution found for Django==2.1.6
You are using pip version 19.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

And I actually don't get your point: even if this succeed, how this helps me to start healthy mailman-web container from the image?

**Comment by danil-smirnov** [comment]
@maxking I've found that the very same error now throws when I try to run _maxking/mailman-web:latest_ as well. Would you like me to create another issue for it?

I've found this article about this error (note the second answer):
https://stackoverflow.com/questions/51903606/errors-when-i-try-to-migrate-in-django2

Has a new field been added into some table in the DB?

By the way I'm creating DB just before containers in any cases so this migrations error happens againsts an empty database.

**Comment by maxking** [comment]
Can you retry the `maxking/postorius:latest` image and see if it still causes a traceback?

**Comment by danil-smirnov** [comment]
@maxking I assume you mean _maxking/postorius:rolling_ not _latest_ as there is no _latest_ tag in the repo...

At this time the error is slightly different:

```
Postgres is up - continuing
Creating log file for mailman web
Creating log file for uwsgi..
settings_local.py not found, it is highly recommended that you provide one
Using default configuration to run.

150 static files copied to '/opt/mailman-web-data/static'.
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, django_mailman3, openid, postorius, sessions, sites, socialaccount
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying account.0001_initial... OK
  Applying account.0002_email_max_length... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sites.0001_initial... OK
  Applying django_mailman3.0001_initial... OK
  Applying django_mailman3.0002_maildomain... OK
  Applying openid.0001_initial... OK
  Applying postorius.0001_initial... OK
  Applying postorius.0002_auto_20160210_0721... OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: syntax error at or near "WITH ORDINALITY"
LINE 6:                     FROM unnest(c.conkey) WITH ORDINALITY co...
                                                  ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 150, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 467, in remove_field
    fk_names = self._constraint_names(model, [field.column], foreign_key=True)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 1029, in _constraint_names
    constraints = self.connection.introspection.get_constraints(cursor, model._meta.db_table)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/introspection.py", line 158, in get_constraints
    """, ["public", table_name])
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: syntax error at or near "WITH ORDINALITY"
LINE 6:                     FROM unnest(c.conkey) WITH ORDINALITY co...
                                                  ^

```

**Comment by danil-smirnov** [comment]
Hi @maxking 
I've done more testing using _mailman-web_ image and I now have clearer view on the issue.
I'm still not able to up mailman-web container from versions _latest_ as well as _0.2_ with the same error.
But if I up version _0.1.7_ first, and then I upgrade the container using `docker-compose down ; docker-compose pull ; docker-compose up -d` command, everything go fine:

```
settings_local.py not found, it is highly recommended that you provide one
Using default configuration to run.
Postgres is up - continuing

71 static files copied to '/opt/mailman-web-data/static', 317 unmodified.
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, django_mailman3, django_q, hyperkitty, openid, postorius, sessions, sites, socialaccount
Running migrations:
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying hyperkitty.0016_auto_20180309_0056... OK
  Applying hyperkitty.0017_file_attachments... OK
  Applying postorius.0004_create_email_template... OK
  Applying postorius.0005_auto_20180707_1107... OK
  Applying postorius.0006_auto_20180711_1359... OK
  Applying postorius.0007_auto_20180712_0536... OK
Creating admin user admin ...
Superuser admin already exists
```

I hope this helps to debug the issue.

**Comment by maxking** [comment]
`docker-compose down ; docker-compose pull ; docker-compose up -d` This doesn't really boot up the container with the new image, it only re-starts the old container.

For `docker-compose` to re-use the new image, you need to do `docker-compose down; docker-compose rm; docker-compose pull; docker-compose up -d`

**Comment by danil-smirnov** [comment]
@maxking You probably right in case you don't change the image version in docker-compose.yaml file; I've done this before the command.

This is what I had after version _0.1.7_ deployed:

![screenshot_4](https://user-images.githubusercontent.com/27999539/53441731-1a801480-3a10-11e9-89df-c3496f767e63.png)

After changing mailman-web image version to _latest_ in docker-compose.yaml and issuing `docker-compose down ; docker-compose pull ; docker-compose up -d` I've got this:

![screenshot_5](https://user-images.githubusercontent.com/27999539/53441834-59ae6580-3a10-11e9-85b6-c6b16ec6c4d5.png)

As you can see, mailman-web container version has been upgraded.

Now could we move to debugging of the issue please? :)

**Comment by maxking** [comment]
I seems like Django dropped support for Postgres < 9.3 in the 2.1 release (https://docs.djangoproject.com/en/2.1/releases/2.1/#dropped-support-for-postgresql-9-3) which seems to be causing your problem. Another instance of a similar issue (https://stackoverflow.com/questions/51827843/django-2-0-7-syntax-error-while-doing-rename-field-migration)

**Comment by danil-smirnov** [comment]
@maxking You are right, the error has gone after I've upgraded PostgreSQL to 9.6.
Thank you very much for your help!
