### ISSUE TITLE
Unable to connect to socket, 500 Internal Server Error

### ISSUE THREAD

**Issue by anthony-halim** [maxking/docker-mailman#340]
Hi, I am having trouble with the GNU Mailman. This error happens in any process that need to send messages (signing up, creating new thread, etc). So far everything else (creating lists, REST API, adding domain, using superuser, front-end) looks fine. 

Here is the error log 
```
ERROR 2019-07-16 07:45:47,805 24 django.request Internal Server Error: /hyperkitty/list/example@hermes.com/message/new
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hyperkitty/lib/view_helpers.py", line 134, in inner
    return func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hyperkitty/views/message.py", line 216, in new_message
    form.cleaned_data["message"], headers)
  File "/usr/lib/python3.6/site-packages/hyperkitty/lib/posting.py", line 106, in post_to_list
    msg.send()  # Don't send mail in debug mode, just in case...
  File "/usr/lib/python3.6/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/usr/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```
At least, is there any way to find out which socket or processes it is trying to connect? I could try to debug by myself from there.

**Comment by maxking** [comment]
https://github.com/maxking/docker-mailman#mailman-web

See the last part of this section on how to configure Django to send out emails. I believe this should also be added to "Setting up the MTA" section, because that seems to be the more appropriate place for it.

**Comment by anthony-halim** [comment]
I have added that to my settings_local.py. FYI, I also have confirmed that my postfix is able to relay from 172.19.199.2 & 172.19.199.3 through 172.19.199.1 by 
1. Going into either 172.19.199.2 or 172.19.199.3
2. installing telnet inside the said container
3. sending email from there

**Comment by maxking** [comment]
172.19.199.1 is the IP of the host, so if Postfix is running on the host and listening on all interfaces, then this would work.

You could just change your settings to point SMTP to 172.19.199.5 in both settings_local.py and mailman-extra.cfg

**Comment by anthony-halim** [comment]
Hi, that works. Thank you so much for your help!
