### ISSUE TITLE
[BUG] Postorius container failing to start

### ISSUE THREAD

**Issue by danil-smirnov** [maxking/docker-mailman#359]
**Tag/version of Container Images**
latest (=0.3.2)

When try to start maxking/postorius container, I'm getting the following error:

```
                                    List of databases
     Name      |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
---------------+----------+----------+-------------+-------------+-----------------------
 - censored - | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 mailman-test  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 - censored -  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 postgres      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
               |          |          |             |             | postgres=CTc/postgres
 template1     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | postgres=CTc/postgres+
               |          |          |             |             | =c/postgres
(6 rows)

settings_local.py not found, it is highly recommended that you provide one
Using default configuration to run.
Postgres is up - continuing
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 104, in collect
    for finder in get_finders():
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/finders.py", line 283, in get_finders
    yield get_finder(finder_path)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/finders.py", line 292, in get_finder
    Finder = import_string(import_path)
  File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'compressor'
```

I also think images urls should be changed in [the configuration sample](https://github.com/maxking/docker-mailman/blob/master/docker-compose-postorius.yaml) from Quay.io to Dockerhub.

**Comment by maxking** [comment]
This is a little strange, because looking at the current version does not include `compressor` in the `INSTALLED_APPS` for Postorius : https://github.com/maxking/docker-mailman/blob/master/postorius/mailman-web/settings.py#L70
Is it possible that you might be working with an old release? Can you bump to the `0.3.2` tag and see if the problem still exists?

**Comment by maxking** [comment]
And I agree that the compose files should use the dokcerhub, since I work more closely on that instead of Quay, which sometimes falls off my radar.

**Comment by danil-smirnov** [comment]
> Is it possible that you might be working with an old release? Can you bump to the `0.3.2` tag and see if the problem still exists?

I've explicitly set version `maxking/postorius:0.3.2` in my `docker-compose.yaml` (used `latest` previously) and I've got the same error again.

I suppose the error relates to `docker-entrypoint.sh` logic not to the application itself.

Also I assume we should have the same base image for the both variants of mailman-web images (if there is no strong reason for the opposite).

**Comment by danil-smirnov** [comment]
Hi,

I've just discovered that we have this bug fixed in `maxking/postorius:latest` image but not in `maxking/postorius:0.3` and `maxking/postorius:0.3.2` images.

Could you please update them to the `latest` for consistency?

Thanks
