### ISSUE TITLE
[BUG] Unable to mass subscribe when [list:user:notice:welcome] is listed as a custom template

### ISSUE THREAD

**Issue by brianemwd** [maxking/docker-mailman#368]
**0.3.1 0.3.2**
When you choose [list:user:notice:welcome] to customized as a template via Postorius, the mass subscribe function throws an exception. This happens even if the template is empty but listed within the Templates page. Here is the exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mailmanclient/restbase/connection.py", line 96, in call
    headers=headers)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/postorius/auth/decorators.py", line 38, in wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/postorius/views/list.py", line 438, in list_mass_subscribe
    pre_approved=True)
  File "/usr/lib/python3.6/site-packages/mailmanclient/restobjects/mailinglist.py", line 304, in subscribe
    response, content = self._connection.call('members', data)
  File "/usr/lib/python3.6/site-packages/mailmanclient/restbase/connection.py", line 119, in call
    raise MailmanConnectionError('Could not connect to Mailman API')
mailmanclient.restbase.connection.MailmanConnectionError: Could not connect to Mailman API
ERROR 2020-03-07 14:31:59,424 20 django.request Service Unavailable: /postorius/lists/onion.mailman3.emwd.com/mass_subscribe/
ERROR 2020-03-07 14:31:59,424 20 django.request Service Unavailable: /postorius/lists/onion.mailman3.emwd.com/mass_subscribe/
ERROR 2020-03-07 14:31:59,404 20 postorius.middleware Mailman REST API not available

**Comment by Falcais** [comment]
I encountered the same problem today after a new setup.
Could someone already solve this?

**Comment by pityonline** [comment]
Similar problem here. Customizing `[list:user:notice:welcome]` and `[list:user:notice:goodbye]` works for me, but not `[list:user:action:subscribe]`, same error in `/opt/mailman/web/logs/mailmanweb.log`. On web interface, it says:

> Mailman REST API not available. Please start Mailman core.

This only affects to a list when `[list:user:action:subscribe]` is set, other lists are ok if I keep it default.

**Comment by pityonline** [comment]
Update: it seems that only `anonymous_subscribe` is affected.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mailmanclient/restbase/connection.py", line 96, in call
    headers=headers)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/postorius/views/generic.py", line 74, in dispatch
    return super(MailingListView, self).dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/postorius/views/list.py", line 396, in post
    pre_confirmed=False)
  File "/usr/lib/python3.6/site-packages/mailmanclient/restobjects/mailinglist.py", line 304, in subscribe
    response, content = self._connection.call('members', data)
  File "/usr/lib/python3.6/site-packages/mailmanclient/restbase/connection.py", line 119, in call
    raise MailmanConnectionError('Could not connect to Mailman API')
mailmanclient.restbase.connection.MailmanConnectionError: Could not connect to Mailman API
ERROR 2020-08-05 11:54:00,569 14 django.request Service Unavailable: /postorius/lists/lists.example.com/anonymous_subscribe
ERROR 2020-08-05 11:54:00,569 14 django.request Service Unavailable: /postorius/lists/lists.example.com/anonymous_subscribe
```

**Comment by pityonline** [comment]
OK, I mixed with another list, logged-in users are also affected.

```
ERROR 2020-08-05 12:54:36,339 14 django.request Service Unavailable: /postorius/lists/lists.example.com/subscribe
ERROR 2020-08-05 12:54:36,339 14 django.request Service Unavailable: /postorius/lists/lists.example.com/subscribe
```

**Comment by pgollor** [comment]
For me it fails with customized `[list:user:notice:welcome]` domain template for anonymous user.

**Comment by Hippu** [comment]
This issue seems to happen when mailman-core and mailman-web containers are trying to do GET-requests that depend on each other.

From my understanding the templates in Mailman 3 should work something like this:

```
[mailman-web] --- subscription request---> [mailman-core]

[mailman-web] <---get template text ------  [mailman-core]
[mailman-web] -- return template text --->  [mailman-core]

[mailman-web] <-- subscription req OK ---  [mailman-core]
```
But for some reason this process fails with a timeout. My guess is that the problem is related to the fact that these HTTP calls are supposed to be work concurrently.

When I try to manually do a template request in a Python prompt inside the Mailman Core container it works as it should.

```
>>> requests.get("http://mailman-web:8000/postorius/api/templates/list/testlist.list.ayy.fi/list:user:notice:goodbye", timeout=5)

<Response [200]>
```

I don't know if the bug is caused by the way that these docker containers are configured or whether the bug exists somewhere upstream.

**Comment by Hippu** [comment]
I took a look at the uwsgi logs and noticed that the template text request from core only returns after the first request times out.
```
[pid: 1695|app: 0|req: 30149/30149] XX.XX.XX.XX () {62 vars in 1649 bytes} [Fri Jan 29 14:52:12 2021] POST /postorius/lists/teemun-testilista.list.ayy.fi/members/member/ => generated 5425 bytes in 5817 msecs (HTTP/1.1 503) 5 headers in 180 bytes (1 switches on core 0)
[pid: 1695|app: 0|req: 30150/30150] 172.19.199.2 () {28 vars in 501 bytes} [Fri Jan 29 14:52:18 2021] GET /postorius/api/templates/list/teemun-testilista.list.ayy.fi/list:user:notice:goodbye => generated 8 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 161 bytes (1 switches on core 0)
```

**Comment by danil-smirnov** [comment]
https://github.com/maxking/docker-mailman/pull/429 is needed as well
