### ISSUE TITLE
mailman-web constantly restarting over and over again

### ISSUE THREAD

**Issue by s0ftcorn** [maxking/docker-mailman#381]
I updated using docker-compose pull. Since then the mailman-web container is constantly restarting.
Here are the logs:

                               List of databases
   Name    |  Owner  | Encoding |  Collate   |   Ctype    |  Access privileges  
-----------+---------+----------+------------+------------+---------------------
 mailmandb | mailman | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres  | mailman | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | mailman | UTF8     | en_US.utf8 | en_US.utf8 | =c/mailman         +
           |         |          |            |            | mailman=CTc/mailman
 template1 | mailman | UTF8     | en_US.utf8 | en_US.utf8 | =c/mailman         +
           |         |          |            |            | mailman=CTc/mailman
(4 rows)

Postgres is up - continuing
Copying settings_local.py ...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'paintstore'

**Comment by maxking** [comment]
What are the contents of your `settings_local.py`.

**Comment by s0ftcorn** [comment]
# Application definition
  
INSTALLED_APPS = (
        'hyperkitty',
        'postorius',
        'django_mailman3',
        # Uncomment the next line to enable the admin:
        'django.contrib.admin',
        # Uncomment the next line to enable admin documentation:
        # 'django.contrib.admindocs',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.sites',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'rest_framework',
        'django_gravatar',
        'paintstore',
        'compressor',
        'haystack',
        'django_extensions',
        'django_q',
        'allauth',
        'allauth.account',
        'allauth.socialaccount',
        'django_mailman3.lib.auth.fedora',
)

**Comment by s0ftcorn** [comment]
Removing 'paintstore', from `settings_local.py` seems to fix the problem.
