### ISSUE TITLE
Increase Gunicorn Workers

### ISSUE THREAD

**Issue by brianemwd** [maxking/docker-mailman#387]
How do I increase the amount of gunicorn workers that your Docker version of Mailman 3 uses? I want to use 4 instead of 2

**Comment by maxking** [comment]
On Wed, Jul 15, 2020, at 1:37 PM, brianemwd wrote:
> How do I increase the amount of gunicorn workers that your Docker version of Mailman 3 uses? I want to use 4 instead of 2



Update mailman.cfg (using `/opt/mailman/core/mailman-extra.cfg` if you are using default settings location for the images)

[webservice]
workers: 4

**Comment by brianemwd** [comment]
Thank you. Unfortunately, that did not solve the main issue I am having which is trying a csv export of a list of 3000 members. This is the error:

ERROR 2020-07-15 21:41:16,267 15 postorius Mailman REST API not available
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

What other settings can I apply that will allow the export of 3000 list members? BTW - your answer does work. I now have 4 workers running. I was hoping that would solve the above issue.

**Comment by maxking** [comment]
Well, you can just run `mailman members` command from the mailman core container to get the list of members. That's all in the csv file anyway.

The issues seems to be due to timeout not due to high load. You want to increase the timeout for gunicorn and you can do that by specifying a gunicorn.ini config file:

```
[webservice]
configuration: /path/to/gunicorn.cfg
```

and then in the gunicorn.cfg you can add
```
[gunicorn]
timeout = 90
graceful_timeout = 30
```
sample one included in mailman: https://gitlab.com/mailman/mailman/-/blob/master/src/mailman/config/gunicorn.cfg

**Comment by brianemwd** [comment]
So I got around and added this to mailman-core via /opt/mailman/core/mailman-extra.cfg:

[webservice]
hostname: mailman-core
configuration: /opt/mailman/gunicorn.cfg



After restarting docker-mailman, I can't access Postorius due to the following error:

ERROR 2020-07-20 20:16:27,351 15 postorius Mailman REST API not available
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f96340a2e10>: Failed to establish a new con$

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen


Commenting out "configuration: /opt/mailman/gunicorn.cfg" brings Postorius back up.

**Comment by brianemwd** [comment]
Still waiting on assistance with this please.

**Comment by maxking** [comment]
Did you also put `gunicorn.cfg` with the timeout at `/opt/mailman/core/gunicorn.cfg` on your host? Can you enter the container and make sure the config file is available at `/opt/mailman/gunicorn.cfg` inside the container? (Note the paths are different on host and inside the container.

Can you enter the container to check if Mailman Core is running (specifically, gunicorn), if not, are there any exceptions in the logs for Core?

**Comment by brianemwd** [comment]
I don't think gunicorn is running. No errors in /opt/mailman/core/var/logs/mailman.log. Yes, I placed the gunicorn.cfg in /opt/mailman/core/. It shows in /opt/mailman/gunicorn.cfg within the container.

**Comment by brianemwd** [comment]
I have this in the gunicorn.cfg file:

[gunicorn]
timeout = 900
graceful_timeout = 180

**Comment by brianemwd** [comment]
Still waiting for a resolution to this.

**Comment by maxking** [comment]
What are the permissions on the gunicorn.cfg file? When you enter the container as `mailman` user, are you able to read the file? Maybe try setting 777 as permissions just to verify that Mailman is actually able to read the file.

It seems weird to me that there are no errors in mailman.log. If Mailman was unable to read gunicorn.cfg it should’ve logged something. 

After starting the container, when you enter the container, what do you see in the `/etc/mailman.cfg` config file?

**Comment by maxking** [comment]
Closing this as once can now override gunicorn configuration in mailman core.
