### ISSUE TITLE
[BUG] Core container won't up after upgrade

### ISSUE THREAD

**Issue by danil-smirnov** [maxking/docker-mailman#401]
**Tag/version of Container Images**
Core 0.3.7

I've discovered that after some recent release Mailman Core container won't `docker-compose up` after its version has upgraded in the docker-compose.yaml file.

The container fails to start with an error:
```
lists-mailman-core | Postgres is up - continuing
lists-mailman-core | Using Postfix configuration
lists-mailman-core | Found configuration file at /opt/mailman/mailman-extra.cfg
lists-mailman-core | Traceback (most recent call last):
lists-mailman-core |   File "/usr/lib/python3.8/site-packages/mailman/bin/master.py", line 125, in acquire_lock_1
lists-mailman-core |     lock.lock(timedelta(seconds=0.1))
lists-mailman-core |   File "/usr/lib/python3.8/site-packages/flufl/lock/_lockfile.py", line 364, in lock
lists-mailman-core |     raise TimeOutError('Could not acquire the lock')
lists-mailman-core | flufl.lock._lockfile.TimeOutError: Could not acquire the lock
lists-mailman-core |
lists-mailman-core | During handling of the above exception, another exception occurred:
lists-mailman-core |
lists-mailman-core | Traceback (most recent call last):
lists-mailman-core |   File "/usr/bin/master", line 8, in <module>
lists-mailman-core |     sys.exit(main())
lists-mailman-core |   File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
lists-mailman-core |     return self.main(*args, **kwargs)
lists-mailman-core |   File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
lists-mailman-core |     rv = self.invoke(ctx)
lists-mailman-core |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
lists-mailman-core |     return ctx.invoke(self.callback, **ctx.params)
lists-mailman-core |   File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
lists-mailman-core |     return callback(*args, **kwargs)
lists-mailman-core |   File "/usr/lib/python3.8/site-packages/mailman/bin/master.py", line 572, in main
lists-mailman-core |     lock = acquire_lock(force)
lists-mailman-core |   File "/usr/lib/python3.8/site-packages/mailman/bin/master.py", line 146, in acquire_lock
lists-mailman-core |     lock = acquire_lock_1(force)
lists-mailman-core |   File "/usr/lib/python3.8/site-packages/mailman/bin/master.py", line 131, in acquire_lock_1
lists-mailman-core |     lock.disown()
lists-mailman-core | AttributeError: 'Lock' object has no attribute 'disown'
```

A workaround is `rm -f core/var/locks/master.lck*` but I suppose it should not happen.

**Comment by danil-smirnov** [comment]
Seems I can not reproduce it
