### ISSUE TITLE
HTTP Error 400:  when adding users to new lists

### ISSUE THREAD

**Issue by gholman** [maxking/docker-mailman#424]
I am running mailman-core,web in Docker environment.  

For the first couple lists I create, adding users occurs without error.   
Now on newly created lists I receive the following error when adding users:

**HTTP Error 400: HTTPConnectionPool(host='mailman-web', port=8000): Read timed out. (read timeout=5)** 

With this rolling version, the users are indeed added.  Previous versions I would receive the error and the users were not added.

Apache config
----------------------------------

```
Alias /static/ /opt/mailman/web/static/
<VirtualHost *:80>
    ServerName <removed >
    Redirect permanent / <removed >
</VirtualHost>

<VirtualHost *:443>
        ServerName <removed >
        SSLEngine On
	Include /etc/letsencrypt/options-ssl-apache.conf
	SSLProxyEngine on

    <Location />
            ProxyPass  uwsgi://172.19.199.3:8080/
    </Location>

         SSLCertificateFile  <removed >
         SSLCertificateKeyFile <removed >
</VirtualHost>
```

Environment: 
----------------------------------
Mailman Core Version | GNU Mailman 3.3.3b1 (Tom Sawyer)
Mailman Core API Version | 3.1
Mailman Core Python Version | 3.8.5 (default, Jul 20 2020, 23:11:29)  [GCC 9.3.0]
Docker version 19.03.6, build 369ce74a3c
Server version: Apache/2.4.29 (Ubuntu)
Linux 5.3.0-1030-aws #32~18.04.1-Ubuntu SMP Tue Jun 30 23:04:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Images: maxking/mailman-web:rolling, maxking/mailman-core:rolling

**Comment by gangefors** [comment]
I've started seeing this error in the logs as well.

This is related to using custom templates. I have validated the following troublesome templates.

[list:user:notice:welcome]  (causes issues when subscribing users)
[list:user:notice:goodbye]  (causes issues when unsubscribing users)

However, these templates works when a user sends mail as a form of subscribing and unsubscribing. It's when using the web ui these actions fails if the template code is triggered.


Environment:
https://github.com/gangefors/aws-mailman3
mailman-core:0.3.11
mailman-web:0.3.6

Full stack trace when subscribing. Notice the `send_welcome_message` in the stack.
```
Mar 18 21:50:39 2021 (49) deque: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='mailman-web', port=8000): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mailman/app/workflow.py", line 69, in __next__
    return step()
  File "/usr/lib/python3.8/site-packages/mailman/app/subscriptions.py", line 343, in _step_do_subscription
    self.member = self.mlist.subscribe(
  File "/usr/lib/python3.8/site-packages/mailman/database/transaction.py", line 85, in wrapper
    return function(args[0], config.db.store, *args[1:], **kws)
  File "/usr/lib/python3.8/site-packages/mailman/model/mailinglist.py", line 507, in subscribe
    notify(SubscriptionEvent(
  File "/usr/lib/python3.8/site-packages/zope/event/__init__.py", line 32, in notify
    subscriber(event)
  File "/usr/lib/python3.8/site-packages/mailman/app/membership.py", line 176, in handle_SubscriptionEvent
    send_welcome_message(mlist, member, member.preferred_language)
  File "/usr/lib/python3.8/site-packages/mailman/app/notifications.py", line 51, in send_welcome_message
    welcome_message = wrap(getUtility(ITemplateLoader).get(
  File "/usr/lib/python3.8/site-packages/mailman/model/template.py", line 188, in get
    contents = getUtility(ITemplateManager).get(
  File "/usr/lib/python3.8/site-packages/mailman/database/transaction.py", line 85, in wrapper
    return function(args[0], config.db.store, *args[1:], **kws)
  File "/usr/lib/python3.8/site-packages/mailman/model/template.py", line 110, in get
    contents = protocols.get(actual_uri, **auth)
  File "/usr/lib/python3.8/site-packages/mailman/utilities/protocols.py", line 38, in get
    response = requests.get(url, timeout=REQUEST_TIMEOUT, **kws)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='mailman-web', port=8000): Read timed out. (read timeout=5)

```

**Comment by maxking** [comment]
@gangefors The timeout issue should've been fixed in 0.3.11 image of mailman-web, you want to upgrade to that to get the fixes.

**Comment by maxking** [comment]
I see that the issue was created before the release of 0.3.11, which should now be released. @gholman you can check with the new released version. I'll go ahead and close this issue now.

**Comment by gangefors** [comment]
Can confirm that it's working fine with 0.3.11. Thanks for letting me know.

Dockerhub is the worst when it comes to how it sorts tags by default. When I looked yesterday 0.3.6 was listed before 0.3.11 for mailman-web while 0.3.11 was listed at the top for mailman-core. 😠
