### ISSUE TITLE
[BUG] mailman-core is looking for MySQL on the PostgreSQL port and so fails to start

### ISSUE THREAD

**Issue by unikitty37** [maxking/docker-mailman#425]
When using `docker-compose-mysql.yaml`, the `mailman-core` container will not come up.

The only changes I have made are to put the config volume in a different location:

```yaml
version: '2'

services:
  mailman-core:
    image: maxking/mailman-core:0.3
    container_name: mailman-core
    hostname: mailman-core
    volumes:
    - /mailman/config/core:/opt/mailman
    links:
    - database:database
    depends_on:
    - database
    environment:
    - DATABASE_URL=mysql+pymysql://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=mysql
    - DATABASE_CLASS=mailman.database.mysql.MySQLDatabase
    - HYPERKITTY_API_KEY=someapikey
    networks:
      mailman:
        ipv4_address: 172.19.199.2

  mailman-web:
    image: maxking/mailman-web:0.3
    container_name: mailman-web
    hostname: mailman-web
    ports:
      - 8000:8000
      - 8080:8080
    depends_on:
    - database
    links:
    - mailman-core:mailman-core
    - database:database
    volumes:
    - /mailman/config/web:/opt/mailman-web-data
    environment:
    - DATABASE_URL=mysql://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=mysql
    - HYPERKITTY_API_KEY=someapikey
    - SECRET_KEY=thisisaverysecretkey
    - DYLD_LIBRARY_PATH=/usr/local/mysql/lib/
    networks:
      mailman:
        ipv4_address: 172.19.199.3

  database:
    environment:
      MYSQL_DATABASE: mailmandb
      MYSQL_USER: mailman
      MYSQL_PASSWORD: mailmanpass
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    restart: always
    image: mariadb:10.3
    volumes:
    - /mailman/config/database:/var/lib/mysql
    networks:
      mailman:
        ipv4_address: 172.19.199.4

networks:
   mailman:
     driver: bridge
     ipam:
       driver: default
       config:
       -
         subnet: 172.19.199.0/24
```

The logs show it appears to be looking for the database on port 5432 — the PostgreSQL port — rather than MySQL's 3306:

```
mailman-core    | No MTA environment variable found, defaulting to Exim
mailman-core    | Found configuration file at /opt/mailman/mailman-extra.cfg
mailman-core    | HYPERKITTY_URL not set, using the default value of http://mailman-web:8000/hyperkitty
mailman-core    | Traceback (most recent call last):
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
mailman-core    |     return fn()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
mailman-core    |     return _ConnectionFairy._checkout(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
mailman-core    |     fairy = _ConnectionRecord.checkout(pool)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
mailman-core    |     rec = pool._do_get()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
mailman-core    |     self._dec_overflow()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
mailman-core    |     compat.raise_(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
mailman-core    |     raise exception
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
mailman-core    |     return self._create_connection()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
mailman-core    |     return _ConnectionRecord(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
mailman-core    |     self.__connect(first_connect_check=True)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
mailman-core    |     pool.logger.debug("Error on connect(): %s", e)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
mailman-core    |     compat.raise_(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
mailman-core    |     raise exception
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
mailman-core    |     connection = pool._invoke_creator(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
mailman-core    |     return dialect.connect(*cargs, **cparams)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
mailman-core    |     return self.dbapi.connect(*cargs, **cparams)
mailman-core    |   File "/usr/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
mailman-core    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
mailman-core    | psycopg2.OperationalError: could not connect to server: Connection refused
mailman-core    | 	Is the server running on host "database" (172.19.199.4) and accepting
mailman-core    | 	TCP/IP connections on port 5432?
mailman-core    |
mailman-core    |
mailman-core    | The above exception was the direct cause of the following exception:
mailman-core    |
mailman-core    | Traceback (most recent call last):
mailman-core    |   File "/usr/bin/mailman", line 8, in <module>
mailman-core    |     sys.exit(main())
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
mailman-core    |     return self.main(*args, **kwargs)
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 781, in main
mailman-core    |     with self.make_context(prog_name, args, **extra) as ctx:
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 700, in make_context
mailman-core    |     self.parse_args(ctx, args)
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1212, in parse_args
mailman-core    |     rest = Command.parse_args(self, ctx, args)
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
mailman-core    |     value, args = param.handle_parse_result(ctx, opts, args)
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
mailman-core    |     value = invoke_param_callback(self.callback, ctx, self, value)
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
mailman-core    |     return callback(ctx, param, value)
mailman-core    |   File "/usr/lib/python3.8/site-packages/mailman/bin/mailman.py", line 94, in initialize_config
mailman-core    |     initialize(value)
mailman-core    |   File "/usr/lib/python3.8/site-packages/mailman/core/initialize.py", line 218, in initialize
mailman-core    |     initialize_2(propagate_logs=propagate_logs)
mailman-core    |   File "/usr/lib/python3.8/site-packages/mailman/core/initialize.py", line 177, in initialize_2
mailman-core    |     config.db = getUtility(IDatabaseFactory, utility_name).create()
mailman-core    |   File "/usr/lib/python3.8/site-packages/mailman/database/factory.py", line 55, in create
mailman-core    |     SchemaManager(database).setup_database()
mailman-core    |   File "/usr/lib/python3.8/site-packages/mailman/database/factory.py", line 83, in setup_database
mailman-core    |     context = MigrationContext.configure(self._database.store.connection())
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1138, in connection
mailman-core    |     return self._connection_for_bind(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1146, in _connection_for_bind
mailman-core    |     return self.transaction._connection_for_bind(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
mailman-core    |     conn = bind._contextual_connect()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
mailman-core    |     self._wrap_pool_connect(self.pool.connect, None),
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
mailman-core    |     Connection._handle_dbapi_exception_noconnection(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
mailman-core    |     util.raise_(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
mailman-core    |     raise exception
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
mailman-core    |     return fn()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
mailman-core    |     return _ConnectionFairy._checkout(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
mailman-core    |     fairy = _ConnectionRecord.checkout(pool)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
mailman-core    |     rec = pool._do_get()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
mailman-core    |     self._dec_overflow()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
mailman-core    |     compat.raise_(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
mailman-core    |     raise exception
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
mailman-core    |     return self._create_connection()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
mailman-core    |     return _ConnectionRecord(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
mailman-core    |     self.__connect(first_connect_check=True)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
mailman-core    |     pool.logger.debug("Error on connect(): %s", e)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
mailman-core    |     compat.raise_(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
mailman-core    |     raise exception
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
mailman-core    |     connection = pool._invoke_creator(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
mailman-core    |     return dialect.connect(*cargs, **cparams)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
mailman-core    |     return self.dbapi.connect(*cargs, **cparams)
mailman-core    |   File "/usr/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
mailman-core    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
mailman-core    | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
mailman-core    | 	Is the server running on host "database" (172.19.199.4) and accepting
mailman-core    | 	TCP/IP connections on port 5432?
mailman-core    |
mailman-core    | (Background on this error at: http://sqlalche.me/e/13/e3q8)
mailman-core    | MySQL is up - continuing
mailman-core    | No MTA environment variable found, defaulting to Exim
mailman-core    | Found configuration file at /opt/mailman/mailman-extra.cfg
mailman-core    | HYPERKITTY_URL not set, using the default value of http://mailman-web:8000/hyperkitty
mailman-core    | Traceback (most recent call last):
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
mailman-core    |     return fn()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
mailman-core    |     return _ConnectionFairy._checkout(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
mailman-core    |     fairy = _ConnectionRecord.checkout(pool)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
mailman-core    |     rec = pool._do_get()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
mailman-core    |     self._dec_overflow()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
mailman-core    |     compat.raise_(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
mailman-core    |     raise exception
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
mailman-core    |     return self._create_connection()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
mailman-core    |     return _ConnectionRecord(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
mailman-core    |     self.__connect(first_connect_check=True)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
mailman-core    |     pool.logger.debug("Error on connect(): %s", e)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
mailman-core    |     compat.raise_(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
mailman-core    |     raise exception
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
mailman-core    |     connection = pool._invoke_creator(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
mailman-core    |     return dialect.connect(*cargs, **cparams)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
mailman-core    |     return self.dbapi.connect(*cargs, **cparams)
mailman-core    |   File "/usr/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
mailman-core    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
mailman-core    | psycopg2.OperationalError: could not connect to server: Connection refused
mailman-core    | 	Is the server running on host "database" (172.19.199.4) and accepting
mailman-core    | 	TCP/IP connections on port 5432?
mailman-core    |
mailman-core    |
mailman-core    | The above exception was the direct cause of the following exception:
mailman-core    |
mailman-core    | Traceback (most recent call last):
mailman-core    |   File "/usr/bin/mailman", line 8, in <module>
mailman-core    |     sys.exit(main())
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
mailman-core    |     return self.main(*args, **kwargs)
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 781, in main
mailman-core    |     with self.make_context(prog_name, args, **extra) as ctx:
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 700, in make_context
mailman-core    |     self.parse_args(ctx, args)
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1212, in parse_args
mailman-core    |     rest = Command.parse_args(self, ctx, args)
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
mailman-core    |     value, args = param.handle_parse_result(ctx, opts, args)
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
mailman-core    |     value = invoke_param_callback(self.callback, ctx, self, value)
mailman-core    |   File "/usr/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
mailman-core    |     return callback(ctx, param, value)
mailman-core    |   File "/usr/lib/python3.8/site-packages/mailman/bin/mailman.py", line 94, in initialize_config
mailman-core    |     initialize(value)
mailman-core    |   File "/usr/lib/python3.8/site-packages/mailman/core/initialize.py", line 218, in initialize
mailman-core    |     initialize_2(propagate_logs=propagate_logs)
mailman-core    |   File "/usr/lib/python3.8/site-packages/mailman/core/initialize.py", line 177, in initialize_2
mailman-core    |     config.db = getUtility(IDatabaseFactory, utility_name).create()
mailman-core    |   File "/usr/lib/python3.8/site-packages/mailman/database/factory.py", line 55, in create
mailman-core    |     SchemaManager(database).setup_database()
mailman-core    |   File "/usr/lib/python3.8/site-packages/mailman/database/factory.py", line 83, in setup_database
mailman-core    |     context = MigrationContext.configure(self._database.store.connection())
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1138, in connection
mailman-core    |     return self._connection_for_bind(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1146, in _connection_for_bind
mailman-core    |     return self.transaction._connection_for_bind(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
mailman-core    |     conn = bind._contextual_connect()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
mailman-core    |     self._wrap_pool_connect(self.pool.connect, None),
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
mailman-core    |     Connection._handle_dbapi_exception_noconnection(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
mailman-core    |     util.raise_(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
mailman-core    |     raise exception
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
mailman-core    |     return fn()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
mailman-core    |     return _ConnectionFairy._checkout(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
mailman-core    |     fairy = _ConnectionRecord.checkout(pool)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
mailman-core    |     rec = pool._do_get()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
mailman-core    |     self._dec_overflow()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
mailman-core    |     compat.raise_(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
mailman-core    |     raise exception
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
mailman-core    |     return self._create_connection()
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
mailman-core    |     return _ConnectionRecord(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
mailman-core    |     self.__connect(first_connect_check=True)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
mailman-core    |     pool.logger.debug("Error on connect(): %s", e)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
mailman-core    |     compat.raise_(
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
mailman-core    |     raise exception
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
mailman-core    |     connection = pool._invoke_creator(self)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
mailman-core    |     return dialect.connect(*cargs, **cparams)
mailman-core    |   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
mailman-core    |     return self.dbapi.connect(*cargs, **cparams)
mailman-core    |   File "/usr/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
mailman-core    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
mailman-core    | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
mailman-core    | 	Is the server running on host "database" (172.19.199.4) and accepting
mailman-core    | 	TCP/IP connections on port 5432?
mailman-core    |
mailman-core    | (Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Tag/version of Container Images**
0.3

**Comment by maxking** [comment]
What is the command that you are using to start up the container? Do you have any other compose files in the same directory?

We run each commit through CI to start up container images and make sure that we are able to reach the API. So this is really weird.

**Comment by unikitty37** [comment]
Just `docker-compose up -d`, with no other compose files.

I removed the entire contents of `/mailman/config` and tried again, and the containers stayed up this time; I'm not sure what happened before. Possibly there was something left in there from a previous attempt using Postgres 😊 

Now I just need to sort out why the web interface is giving "400 Bad Request" rather than a Web UI…

Thanks, and sorry for the spam
