### ISSUE TITLE
How to debug 500 error?

### ISSUE THREAD

**Issue by danil-smirnov** [maxking/docker-mailman#435]
Hi @maxking 

Recently I've upgraded the web image to the latest version and I monitor the logs to ensure it works as expected.

Several times during the last week I witnessed the following errors in the logs which provide no detail regarding the issue:

```
ERROR 2021-02-23 12:57:28,420 1715 postorius Un-handled exception: HTTP Error 500: <html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/postorius/views/generic.py", line 74, in dispatch
    return super(MailingListView, self).dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/postorius/views/list.py", line 276, in get
    self.mailing_list.archivers['hyperkitty']):
  File "/usr/lib/python3.8/site-packages/mailmanclient/restbase/base.py", line 146, in __getitem__
    return self._get(key)
  File "/usr/lib/python3.8/site-packages/mailmanclient/restbase/base.py", line 88, in _get
    return self.rest_data[key]
  File "/usr/lib/python3.8/site-packages/mailmanclient/restbase/base.py", line 74, in rest_data
    response, content = self._connection.call(self._url)
  File "/usr/lib/python3.8/site-packages/mailmanclient/restbase/connection.py", line 127, in call
    raise HTTPError(url, response.status_code,
urllib.error.HTTPError: HTTP Error 500: <html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html>
```

or I see just the following errors:

```
ERROR 2021-02-23 12:33:11,696 1717 django.request Internal Server Error: /hyperkitty/
ERROR 2021-02-23 12:33:11,696 1717 django.request Internal Server Error: /hyperkitty/
```

I tried to find some more logs but failed.

Could you advise how to dig into those errors to identify a root cause please?

**Comment by danil-smirnov** [comment]
Thank you @maxking !
