### ISSUE TITLE
[BUG] error while attempting to bind on address ('172.105.159.180', 8024): address not available

### ISSUE THREAD

**Issue by c4lliope** [maxking/docker-mailman#530]
Running v `0.4`;

On a clean Debian machine running on Linode,
running no other processes besides `sshd` and `nginx`;
I am seeing an error inside the docker container `mailman-core` regarding a binding to port 8024.

I ran a small trace to see which ports on the machine are occupied:
```
root@localhost:~/docker-mailman# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      450/sshd            
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      18314/master        
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      18836/nginx: master 
tcp6       0      0 :::22                   :::*                    LISTEN      450/sshd            
tcp6       0      0 ::1:25                  :::*                    LISTEN      18314/master        
tcp6       0      0 :::443                  :::*                    LISTEN      18836/nginx: master 
```

So nothing seems to be using 8024; I have no way of knowing if it's a commonly used port number,
though as advertised it seems to be used for LMTP, so maybe there is really a background LMTP process
running on my machine undetected.

Regardless, any direction and help will go a long way. Much obliged.

**Comment by c4lliope** [comment]
More detailed logs on `mailman-core` container, varied commands.

```
root@localhost:~/docker-mailman# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@localhost:~/docker-mailman# docker-compose up -d; sleep 4; docker-compose ps; docker logs -f mailman-core
Creating network "docker-mailman_mailman" with driver "bridge"
Creating docker-mailman_database_1 ... done
Creating mailman-core              ... done
Creating mailman-web               ... done
          Name                         Command               State                         Ports                       
-----------------------------------------------------------------------------------------------------------------------
docker-mailman_database_1   docker-entrypoint.sh postgres    Up      5432/tcp                                          
mailman-core                docker-entrypoint.sh maste ...   Up      127.0.0.1:8001->8001/tcp, 127.0.0.1:8024->8024/tcp
mailman-web                 docker-entrypoint.sh uwsgi ...   Up      127.0.0.1:8000->8000/tcp, 127.0.0.1:8080->8080/tcp
                               List of databases
   Name    |  Owner  | Encoding |  Collate   |   Ctype    |  Access privileges  
-----------+---------+----------+------------+------------+---------------------
 mailmandb | mailman | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres  | mailman | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | mailman | UTF8     | en_US.utf8 | en_US.utf8 | =c/mailman         +
           |         |          |            |            | mailman=CTc/mailman
 template1 | mailman | UTF8     | en_US.utf8 | en_US.utf8 | =c/mailman         +
           |         |          |            |            | mailman=CTc/mailman
(4 rows)

Postgres is up - continuing
Using Postfix configuration
Found configuration file at /opt/mailman/mailman-extra.cfg
HYPERKITTY_API_KEY found, setting up HyperKitty archiver...
HYPERKITTY_URL not set, using the default value of http://mailman-web:8000/hyperkitty
Traceback (most recent call last):
  File "/usr/bin/runner", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/mailman/bin/runner.py", line 188, in main
    runner.run()
  File "/usr/lib/python3.8/site-packages/mailman/runners/lmtp.py", line 255, in run
    self.lmtp.start()
  File "/usr/lib/python3.8/site-packages/aiosmtpd/controller.py", line 210, in start
    raise self._thread_exception
  File "/usr/lib/python3.8/site-packages/aiosmtpd/controller.py", line 176, in _run
    srv: AsyncServer = self.loop.run_until_complete(self.server_coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('172.105.159.180', 8024): address not available
^C
root@localhost:~/docker-mailman# docker-compose down
Stopping mailman-web               ... done
Stopping mailman-core              ... done
Stopping docker-mailman_database_1 ... done
Removing mailman-web               ... done
Removing mailman-core              ... done
Removing docker-mailman_database_1 ... done
Removing network docker-mailman_mailman
root@localhost:~/docker-mailman# netstat -tulpn
```

**Comment by c4lliope** [comment]
Looks like `netstat` missed a process binding on 8024:

```
root@localhost:~/docker-mailman# lsof -i TCP | grep 8024
docker-pr  9908     root    4u  IPv4 610205      0t0  TCP localhost:8024 (LISTEN)
root@localhost:~/docker-mailman#
```

**Comment by c4lliope** [comment]
I'll reopen this until I find out what the `docker-pr` process is, it keeps re-spawning and occuping 8024 so I can't open a connection through `mailman-core`. Breaking error, seems like.

**Comment by c4lliope** [comment]
Seems like the `docker-pr` process is a simple binding that appears for every port a container binds on;
it isn't the cause of the blocked port, it represents the connection we're trying to make.

Regardless, I checked the system firewall rules to see if there was a restriction on 8024. All looks fine:
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  0.0.0.0/0            0.0.0.0/0           
DOCKER-ISOLATION-STAGE-1  all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (3 references)
target     prot opt source               destination         
ACCEPT     tcp  --  0.0.0.0/0            172.19.199.3         tcp dpt:8024
ACCEPT     tcp  --  0.0.0.0/0            172.19.199.3         tcp dpt:8001
ACCEPT     tcp  --  0.0.0.0/0            172.19.199.4         tcp dpt:8080
ACCEPT     tcp  --  0.0.0.0/0            172.19.199.4         tcp dpt:8000

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0           
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0           
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-ISOLATION-STAGE-2 (3 references)
target     prot opt source               destination         
DROP       all  --  0.0.0.0/0            0.0.0.0/0           
DROP       all  --  0.0.0.0/0            0.0.0.0/0           
DROP       all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
```

**Comment by c4lliope** [comment]
I also rummaged around inside `docker-compose.yaml` and discovered that deleting the `networks:` configuration blocks from each service did nothing to resolve the networking and port binding issue.

No more real leads to follow;
I may provision a second machine and see if the error follows me.
All I need is one functioning instance of the application.

**Comment by c4lliope** [comment]
@maxking I realize there's a bunch of logs to go through here - do they give you any ideas?
Have you seen problems binding to port 8024 on any other machine?

**Comment by c4lliope** [comment]
Discovered one of the firewall ports - 8024 - on the server was closed, for an unknown reason.
Unrelated to this codebase.

**Comment by c4lliope** [comment]
I was misreading the response from `nmap`, where I did a port scan on my machine; a response saying a port is closed simply means there is no process open on the port, and does not signify that the firewall is in place on the port.

I provisioned a couple more similar machines running Debian,
and loaded `docker-mailman` and hooked up the environment and nginx configuration.
I received the same error.

I found the approach I needed here: https://github.com/maxking/docker-mailman/issues/82
– the thread recommends using `MM_HOSTNAME` to set the internal Docker IP address of the container.

I used a helpful command to locate the IP address:
```
docker network inspect -f '{{json .Containers}}' docker-mailman_mailman |jq '.[] | .Name + ":" + .IPv4Address'
```

**Comment by omnitec** [comment]
On Fri, 17 Dec 2021, Grace wrote:

> I was misreading the response from `nmap`, where I did a port scan on my machine; a response saying a port is closed simply means there is no process open on the port, and does not signify that the firewall is in place on the port.
>
Much simpler to use static IPs, setting in the compose.

	Lee
