### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kordan** [maxking/docker-mailman#536]
**Tag/version of Container Images**
0.4.*

After docker installation, trying to configure mailman-web to use external mysql database. 
I declared the DATABASE_URL variable in docker-compose using the suggested syntax:

DATABASE_URL=mysql://user:OJ<+Rrplusnextpasswordcharcters@host_ip:port/database_name?charset=utf8&use_unicode=1

Upon restarting, I get in logs the following error:

Copying settings_local.py ...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mailman-web/settings.py", line 151, in <module>
    'default': dj_database_url.config(conn_max_age=600)
  File "/usr/lib/python3.8/site-packages/dj_database_url.py", line 55, in config
    config = parse(s, engine, conn_max_age, ssl_require)
  File "/usr/lib/python3.8/site-packages/dj_database_url.py", line 105, in parse
    port = (str(url.port) if url.port and engine == SCHEMES['oracle']
  File "/usr/lib/python3.8/urllib/parse.py", line 174, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'OJ<+Rr'

Trying to insert the same settings in /opt/mailman/web/settings_local.py, after commenting the variable definition in docker-compose leads to the same result.

**Comment by mistermatt2u** [comment]
@kordan Take a look at issue #412 and see if that might help. It seems like your chosen password might include any of /, ?, #, @, or :.
