### ISSUE TITLE
Messages are not archived

### ISSUE THREAD

**Issue by cahitguclu** [maxking/docker-mailman#614]
I installed docker-mailman with mailcow dockerized as described on the mailcow.email site. There is no problem with the transmission of messages. However, mails published in mailman lists do not appear in hyperkitty archives. I can't see any error logs either. How can I find where the problem originates?

**Comment by veixus** [comment]
Im using a letsencrypt SSl sert and it seems its another SSL related bug for mailman. It doesnt seem to accept SSL connections between mailman-core and mailman-web.

Im still looking for a solution, but its this :

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='mywebserver', port=443): Max retries exceeded with url: /hyperkitty/api/mailman/archive (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
[24/Jul/2023:07:00:02 +0000] "GET /3.1/lists?count=10&page=1 HTTP/1.1" 200 488 "-" "GNU Mailman REST client v3.3.5"

```

**Comment by veixus** [comment]
I think I figured it out - seems to be working now:
the hypperkitty connections from mailman-core to mailman-web have to run across plain HTTP otherwise it starts to check CA certificates and breaks and the above problem occurs.

docker-compose.yaml:
`- HYPERKITTY_URL=http://mailman-web:8000/hyperkitty`

This causes an issue with mailman-web when proxying over nginx SSL but I was able to fix it by adding this to 
/opt/mailman/web/settings_local.py: 
`ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.1.1, 'mywebserver.name', '172.19.199.*' ]`

**Comment by almereyda** [comment]
It appears on our end, all was achieved after upgrading the database and then upgrading the `DATABASE_URL` scheme from `postgres://` to `postgresql://`. `The configuration was then working again.

**Comment by theseanl** [comment]
I am having a similar issue, starting from upgrading the host machine to ubuntu 24. 
```
Sep 10 00:35:47 2024 (23) archiving failed, re-queuing (mailing-list [mailing_list_name], message <message_id>)
Sep 10 00:35:47 2024 (23) Exception in the HyperKitty archiver: <html><title>Forbidden</title><body>
                <h1>Access is forbidden</h1><p>Please check the IP addresses
                 assigned to MAILMAN_ARCHIVER_FROM in the settings file.
                </p></body></html>
Sep 10 00:35:47 2024 (23) Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mailman_hyperkitty/__init__.py", line 158, in _archive_message
    url = self._send_message(mlist, msg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mailman_hyperkitty/__init__.py", line 228, in _send_message
    raise ValueError(result.text)
ValueError: <html><title>Forbidden</title><body>
                <h1>Access is forbidden</h1><p>Please check the IP addresses
                 assigned to MAILMAN_ARCHIVER_FROM in the settings file.
                </p></body></html>
```
In ubuntu 24, it seems that `docker-compose` doesn't work, so I had to use `docker compose`.
