### ISSUE TITLE
Add support for postfix

### ISSUE THREAD

**Issue by maxking** [maxking/docker-mailman#7]
Right now the only supported MTA is exim4. This is because of the way different MTA are made aware about the addresses of the existing lists on the server. 

To use postfix, mailman needs access to postmap command, which is supposed to be on the host and not accessible from within the container. A possible workaround for this could be to install postfix inside of the container too and then make it generate transport maps for the postfix installation outside the container.

Exim4 works differently. It can be configured to check for the lists by creating simple files/folders at a predefined location with the names of the lists. Mailman already does thist at `var_dir/lists` which is what we use here.

**Comment by maxking** [comment]
This would mean the MTA needs to be made configurable too!

**Comment by maxking** [comment]
Postfix should now work with the latest image. Add documentation to the pages.

**Comment by ulrith** [comment]
Hi, after successful `composer up` and adding the domain with Django admin I'm unable to create new list. The error is related to postfix support I believe. So I'm adding the report here:

```Jun 11 14:39:49 2017 (35) REST request handler error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/local/lib/python3.6/collections/__init__.py", line 885, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/lib/python3.6/collections/__init__.py", line 877, in __missing__
    raise KeyError(key)
KeyError: 'postmap_command'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.6/site-packages/mailman/database/transaction.py", line 50, in wrapper
    rtn = function(*args, **kws)
  File "/usr/local/lib/python3.6/site-packages/mailman/rest/wsgiapp.py", line 214, in __call__
    return super().__call__(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 227, in __call__
    responder(req, resp, **params)
  File "/usr/local/lib/python3.6/site-packages/mailman/rest/lists.py", line 245, in on_post
    mlist = create_list(**validator(request))
  File "/usr/local/lib/python3.6/site-packages/mailman/app/lifecycle.py", line 100, in create_list
    call_name(config.mta.incoming).create(mlist)
  File "/usr/local/lib/python3.6/site-packages/mailman/utilities/modules.py", line 55, in call_name
    return named_callable(*args, **kws)
  File "/usr/local/lib/python3.6/site-packages/mailman/mta/postfix.py", line 58, in __init__
    self.postmap_command = mta_config.get('postfix', 'postmap_command')
  File "/usr/local/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'postmap_command' in section: 'postfix'
Jun 11 14:39:49 2017 (35) 172.19.199.11 - - "POST /3.0/lists HTTP/1.1" 500 59
```

**Comment by maxking** [comment]
I think I am missing a configuration line in the /etc/postfix-mailman.cfg. I will fix that.

**Comment by maxking** [comment]
@ulrith It should now be fixed with the latest image on the docker hub, which should be available in next 30 mins.

**Comment by ulrith** [comment]
@maxking yes it works now

**Comment by maxking** [comment]
Awesome, closing this issue then :)
