### ISSUE TITLE
Which default address should Mailman Core bind to for LMTP?

### ISSUE THREAD

**Issue by ulrith** [maxking/docker-mailman#82]
Hi, after last updates my Mailman configuration stop working. Now when I up containers I get the following error in mailman-core:

```
test-mailman-core | Postgres is up - continuing
test-mailman-core | Found configuration file at /opt/mailman/mailman-extra.cfg
test-mailman-core | Traceback (most recent call last):
test-mailman-core |   File "/usr/local/bin/runner", line 11, in <module>
test-mailman-core |     sys.exit(main())
test-mailman-core |   File "/usr/local/lib/python3.6/site-packages/mailman/bin/runner.py", line 194, in main
test-mailman-core |     runner = make_runner(*args.runner, once=args.once)
test-mailman-core |   File "/usr/local/lib/python3.6/site-packages/mailman/bin/runner.py", line 94, in make_runner
test-mailman-core |     return runner_class(name, slice)
test-mailman-core |   File "/usr/local/lib/python3.6/site-packages/mailman/runners/rest.py", line 53, in __init__
test-mailman-core |     self._server = make_server()
test-mailman-core |   File "/usr/local/lib/python3.6/site-packages/mailman/rest/wsgiapp.py", line 234, in make_server
test-mailman-core |     handler_class=AdminWebServiceWSGIRequestHandler)
test-mailman-core |   File "/usr/local/lib/python3.6/wsgiref/simple_server.py", line 153, in make_server
test-mailman-core |     server = server_class((host, port), handler_class)
test-mailman-core |   File "/usr/local/lib/python3.6/socketserver.py", line 453, in __init__
test-mailman-core |     self.server_bind()
test-mailman-core |   File "/usr/local/lib/python3.6/wsgiref/simple_server.py", line 50, in server_bind
test-mailman-core |     HTTPServer.server_bind(self)
test-mailman-core |   File "/usr/local/lib/python3.6/http/server.py", line 136, in server_bind
test-mailman-core |     socketserver.TCPServer.server_bind(self)
test-mailman-core |   File "/usr/local/lib/python3.6/socketserver.py", line 467, in server_bind
test-mailman-core |     self.socket.bind(self.server_address)
test-mailman-core | OSError: [Errno 99] Address not available
```

The /opt/mailman/mailman-extra.cfg mentioned is as follows:

```
bash-4.3# cat /opt/mailman/mailman-extra.cfg
[mta]
incoming: mailman.mta.postfix.LMTP
outgoing: mailman.mta.deliver.deliver
lmtp_host: 172.19.199.18
lmtp_port: 8024
smtp_host: 172.19.199.17
smtp_port: 25
configuration: /etc/postfix-mailman.cfg
```

Docker network is configured as follows:

```
[root@host1 test]# docker network inspect test_mailman
[
    {
        "Name": "test_mailman",
        "Id": "37c9994c2089d5b2668ef8654600a216850ea292d263d0a5982b7e6dc7c41e7d",
        "Created": "2017-07-22T14:09:43.285147243+03:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.199.16/29"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "1857292d3af9f1779a63837ae548ad457951c770cf10870e6dd92d695f53a837": {
                "Name": "nginx-proxy",
                "EndpointID": "7034d2d6c6d002d639bbf3089d24e59d6c44cadbc177f841e9052a5dde940752",
                "MacAddress": "02:42:ac:13:c7:15",
                "IPv4Address": "172.19.199.21/29",
                "IPv6Address": ""
            },
            "4499c3af9773be03c3395bd1cddeb064ef164f957815e457c6119cd56fe62a0d": {
                "Name": "test-database",
                "EndpointID": "0baa6d19835206abb413176a9028a8b8da669aa90938b19c3d8e5e2100029506",
                "MacAddress": "02:42:ac:13:c7:14",
                "IPv4Address": "172.19.199.20/29",
                "IPv6Address": ""
            },
            "9b6f03ab97f21822e73e7443f516350db42a88011228104814b62bdefc34f21b": {
                "Name": "test-mailman-core",
                "EndpointID": "a38fba9ccb5f333cd6d44f6c0be50991aa26f73aad3a161379d1f71854137fb9",
                "MacAddress": "02:42:ac:13:c7:12",
                "IPv4Address": "172.19.199.18/29",
                "IPv6Address": ""
            },
            "d0acd784d6ff1750f0d4f6e30294ba79bd3d0771ee82e977cced54b9be18dc6b": {
                "Name": "test-mailman-web",
                "EndpointID": "4afc0c28fe22a1dcbb22281a1ecc6cd053e6e54378601c8232c2fe5b6213fbb4",
                "MacAddress": "02:42:ac:13:c7:13",
                "IPv4Address": "172.19.199.19/29",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

Can we please debug the error?

**Comment by maxking** [comment]
What version of the containers are you using?

**Comment by ulrith** [comment]
Latest

**Comment by maxking** [comment]
https://github.com/maxking/docker-mailman/blob/master/core/assets/run.sh#L31

This might be the culprit, I was suspecting this might be a problem for people not using the compose file exactly like I have planned.

Setting MM_HOSTNAME env var in mailman-core container to the mailman-core IP address *should* fix this problem.

I will try to come up with a better way to do this. Maybe bind to 0.0.0.0 instead by default.

**Comment by ulrith** [comment]
Yes, after passing MM_HOSTNAME environment variable to mailman-core container everything return back to work. Thanks!

**Comment by maxking** [comment]
There are a couple of solutions to this, but I am not sure which one is the best:

First, make it mandatory to set MM_HOSTNAME (possibly rename it to LMTP_HOST) env var and not start the container if it is not set. This is because I don't want to make an assumption about the networking that people would do. But this would also mean that the people deploying it standalone without fixed network would need to know about the Address it will be assigned prior to it is spun out, which might not always be True.

I can't make it a generic 0.0.0.0 because this is used to generate postfix transport maps and 0.0.0.0 in a map would not make any sense. Also the hostname `mailman-core` isn't available by default from the host and hence the problem of routing email to the container persists.

I wonder if there is anything else that I can do here?

**Comment by ulrith** [comment]
I'd suggest just to use a value returned by `hostname -i` instead of any hardcoded value if no MM_HOSTNAME variable set. In your docker-compose.yaml example you implicitly define container's IP address so it should be retrieved and used from inside a container.

**Comment by maxking** [comment]
@ulrith Thanks! I was indeed looking for something like that, didn't know about the command.

**Comment by c4lliope** [comment]
I used a helpful command to locate the IP address:
```
> docker network inspect -f '{{json .Containers}}' docker-mailman_mailman |jq '.[] | .Name + ":" + .IPv4Address'
"docker-mailman_database_1:172.19.199.2/24"
"mailman-core:172.19.199.3/24"
"mailman-web:172.19.199.4/24"
```

**Comment by zoomyboy** [comment]
I'm having the same problem. Wouldn't it be possible to stay with ``lmtp_host: localhost`` and export port 8024 to the host? That way, docker would be responsible for the redirection rather than the container.
